import = [
  # "~/.config/alacritty/themes/themes/alactitty_0_12.toml"
  # "~/.config/alacritty/themes/themes/github_dark_colorblind.toml"
  # "~/.config/alacritty/themes/themes/github_dark_default.toml"
  # "~/.config/alacritty/themes/themes/github_dark_dimmed.toml"
  # "~/.config/alacritty/themes/themes/github_dark_high_contrast.toml"
  # "~/.config/alacritty/themes/themes/github_dark.toml"
  # "~/.config/alacritty/themes/themes/github_dark_tritanopia.toml"
  # "~/.config/alacritty/themes/themes/github_dark_default.toml"
  "~/.config/alacritty/themes/themes/catppuccin_mocha.toml"
  #
  # "~/.config/alacritty/themes/themes/catppuccin_latte.toml"
  # "~/.config/alacritty/themes/themes/atom_one_light.toml"
  # "~/.config/alacritty/themes/themes/ayu_light.toml"
  # "~/.config/alacritty/themes/themes/enfocado_light.toml"
  # "~/.config/alacritty/themes/themes/everforest_light.toml"
  # "~/.config/alacritty/themes/themes/github_light.toml"
  # "~/.config/alacritty/themes/themes/github_light_colorblind.toml"
  # "~/.config/alacritty/themes/themes/github_light_default.toml"
  # "~/.config/alacritty/themes/themes/github_light_tritanopia.toml"
  # "~/.config/alacritty/themes/themes/gruvbox_light.toml"
  # "~/.config/alacritty/themes/themes/gruvbox_material_hard_light.toml"
  # "~/.config/alacritty/themes/themes/gruvbox_material_medium_light.toml"
  # "~/.config/alacritty/themes/themes/papercolor_light.toml"
  # "~/.config/alacritty/themes/themes/papertheme.toml"
  # "~/.config/alacritty/themes/themes/pencil_light.toml"
  # "~/.config/alacritty/themes/themes/rose-pine-dawn.toml"
  # "~/.config/alacritty/themes/themes/solarized_light.toml"
]
live_config_reload = true

#[env]
#TERM = "xterm-256color"
[env]
#  TERM_THEME = "light"
  TERM_THEME = "dark"

[font]
size = 14.0

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Heavy"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Heavy Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Medium Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Medium"

[[keyboard.bindings]]
chars = "\u0002 "
key = "C"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0002\""
key = "E"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002%"
key = "E"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = """
:Grep
"""
key = "F"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002[/"
key = "F"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0002g"
key = "G"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002G"
key = "G"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0002T"
key = "J"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002T"
key = "K"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002L"
key = "L"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002u"
key = "O"
mods = "Command"

[[keyboard.bindings]]
chars = """
:GoToFile
"""
key = "P"
mods = "Command"

[[keyboard.bindings]]
chars = """
:GoToCommand
"""
key = "P"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = """
:q
"""
key = "Q"
mods = "Command"

[[keyboard.bindings]]
chars = """
\u001B:w
"""
key = "S"
mods = "Command"

[[keyboard.bindings]]
chars = """
\u001B:wq
"""
key = "S"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0002c"
key = "T"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002]"
key = "V"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0002P"
key = "T"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0002x"
key = "W"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002z"
key = "Z"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002n"
key = "Tab"
mods = "Control"

# TODO: fix "Grave"
# [[keyboard.bindings]]
# chars = "\u0002p"
# key = "Grave"
# mods = "Control"

[[keyboard.bindings]]
chars = "\u0002,"
key = "Comma"
mods = "Command"

[[keyboard.bindings]]
chars = """
:ZenMode
"""
key = "Period"
mods = "Command"

[[keyboard.bindings]]
chars = "\u000F"
key = "LBracket"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002p"
key = "LBracket"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\t"
key = "RBracket"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002n"
key = "RBracket"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0002:"
key = "Semicolon"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00021"
key = "Key1"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00022"
key = "Key2"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00023"
key = "Key3"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00024"
key = "Key4"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00025"
key = "Key5"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00026"
key = "Key6"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00027"
key = "Key7"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00028"
key = "Key8"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00029"
key = "Key9"
mods = "Command"

[window]
opacity = 0.98
startup_mode = "Maximized"

[window.padding]
# x = 10
# y = 10
x = 10
y = 0
